# Travis CI config
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# https://docs.travis-ci.com/user/customizing-the-build/
# https://docs.travis-ci.com/user/migrating-from-legacy/

filter_secrets: false
language: node_js

node_js:
  - 'lts/*'

install:
  - npm install

before_script:
  - npm run build

script:
  - npm test

jobs:
  include:
    - stage: Deploy
      name: Publish to npm
      script: true
      after_success: true
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_API_KEY
        skip_cleanup: true
        on:
          tags: true
          branch: master
